version: '2'
services:
  mysql:
    build: ./mysql/
    environment:
      # when change the environment, delete mysql_data to reflect the cnanges
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # save mysql data to the folder
      - ./mysql/mysql_data:/var/lib/mysql
      # initiate data
      - ./mysql/sqls:/docker-entrypoint-initdb.d
  mongo:
    image: mongo
    # build: ./mongodb/
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongodb/mongo_data:/data/db
    ports:
      - "27017:21017"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
